version: "3.7"

services:
    puppeteer:
        user: pptruser
        working_dir: /home/pptruser
        build: .
        image: puppeteer-chrome-linux
        container_name: puppeteer-chrome
        volumes:
            - .:/home/pptruser
        cap_add:
            - SYS_ADMIN
        command: 
            - /bin/sh
            - -c
            - |
                ls /home/pptruser -la
                node -e "`cat ./examples/youtube.js`"
            