version: "3.7"

services:
    debian:
        # user:
        working_dir: /app/
        build: .
        image: work_debian_v3
        container_name: work_debian
        volumes:
            - .:/app/
       

