version: "3.6"

services:
  gitlab-runner:
    # build: ./
    # image: gitlab/gitlab-runner:latest
    image: gitlab/gitlab-runner:alpine-v1.11.4
    # image: gitlab/gitlab-runner:v10.8.0
    container_name: gitlab-runner
    working_dir: /etc/gitlab-runner/
    # network_mode: host
    restart: always
    privileged: true
    volumes:
      - ./data:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock

