version: "3.7"

services:
    chrome:
        # user:
        working_dir: /app/
        build: .
        image: puppeteer_handful_v1
        container_name: puppeteer_handful_v1
        volumes:
            - .:/app/
       

